#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SudokuAI.Resource", IsApplication=true)]

namespace SudokuAI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040006
			public const int LLpadding_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int LLpadding_top = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int Llabel_height = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Llabel_width = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int PLpadding_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PLpadding_top = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Plabel_height = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Plabel_width = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020006
			public const int avColor = 2130837510;
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Opening = 2130837505;
			
			// aapt resource value: 0x7f020005
			public const int solvedColor = 2130837509;
			
			// aapt resource value: 0x7f020002
			public const int SudokuGrid = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int txtColorAV = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int txtColorSolved = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int Clear = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int MyImage = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int numberPicker = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NumberPickerDialog = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int NumberPickerTitle = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
